### ISSUE TITLE
Super or this constructor never invoked. How to make call to super()?

### ISSUE THREAD

**Issue by fmcarvalho** [cojen/Maker#11]
I am generating a constructor in a class to initialise a field, which throws `IllegalStateException: Super or this constructor never invoked`.

I am not figuring out how to call the base constructor and cannot find either on documentation.

I have already tried unsuccessfully: 
* `initMaker.invoke("<init>")`  => `IllegalStateException: Unsupported method: <init>`
* `initMaker.invoke("super");` => `IllegalStateException: No matching methods found for: org.cojen.maker.ClassMaker-0.super`
* `initMaker.field("super").invoke("<init>");` =>`IllegalStateException: Field not found in org.cojen.maker.ClassMaker-2: super`

How can we make a call to `super()`?

**Comment by broneill** [comment]
Did you try calling invokeSuperConstructor? Perhaps the documentation needs to be be improved?

**Comment by fmcarvalho** [comment]
Ok, it solves. Yes, documentation is missing that.

P.S. > Great work. I am planning to use this framework in my lectures on Managed Runtime Environments. https://cc.isel.pt/academia/leic-en/lae-en/. It is much easier than ASM and more type safe than manipulating strings with JavaPoet. I didn't like either ByteBuddy nor JavaAssist.

**Comment by broneill** [comment]
What do you recommend for improving the documentation? Something in the javadocs or examples?

**Comment by fmcarvalho** [comment]
I was looking in the Wiki documentation. I like the idea of the "Coding patterns" page. Yet, it is mainly focus on control flow. 
I missed the essentials about building a class from the scratch, namely when we are implementing an interface.

**Comment by broneill** [comment]
I added a new section at the top: https://github.com/cojen/Maker/wiki/Coding-patterns

Does this work?

**Comment by fmcarvalho** [comment]
I think next statement is not entirely true: "_If no explicit call is made, a call to super() is inserted automatically_". That was where I wast stuck, because a I had a constructor initialising a field and no call to `super()` was inserted automatically throwing "`IllegalStateException: Super or this constructor never invoked`"

Maybe it is inserted automatically only if we do not insert any other statement in that constructor.

If you wish I can turn some of the next point in issues of this repo:

1. BTW when I was using dotnet and the `System.Reflection.Emit` framework to do a similar job, there was a nice example that was quite enough for students start building their dynamic generators. This was the main example [AssemblyBuilder](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder?view=net-7.0) and it would be very useful to have some similar example here in Maker. IMHO, the example "Ease-of-use" of this Wiki is not so clear and misses some parts. 

1. Also, another important example missing is a sample about implementing interfaces. Something like this [AddInterfaceImplementation](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder.addinterfaceimplementation?view=net-7.0).

1. Finally, I did not tried yet, but I am very curious to use the `LambdaMetafactory` through Cojen Maker. I have already checked your example of LambdaMetafactory in the wiki, but I would like to try something with a closure capturing variables of an enclosing function. Usually we use dynamic generators techniques to implement an interface, where the implementing class receives the context in constructor parameters and store it in fields. An alternative to that approach is to build a lambda with closure. In that case the generated "lambda$..." delegate method will have additional parameters for each value captured in the closure. I would be very useful to have same example like that.

**Comment by broneill** [comment]
> Maybe it is inserted automatically only if we do not insert any other statement in that constructor.

Oops, you are correct. I updated the page accordingly. This is actually the safest behavior, because I don't know where the super call should appear. Java defines it as the first instruction, but the JVM isn't that strict.

As far as other examples are concerned, I haven't provided much because I don't have the experience of learning how to use the API. You and your students certainly will, and so any examples that you can provide will be greatly appreciated. I don't have any personal attachment to the structure and content of the current wiki pages.

The LambdaMetafactory example isn't complete because proper use of the LambdaMetafactory is extremely complicated. I don't even understand how to use all the different forms. It's primarily designed for the Java compiler, and when I need to define the equivalent of lambdas in my own projects I just define custom indy methods.

The desugar link on that page was broken, but it's now fixed to refer to this: https://cr.openjdk.org/~briangoetz/lambda/lambda-translation.html

**Comment by broneill** [comment]
I'll close this issue for now. New documentation related issues can be opened separately.
