### ISSUE TITLE
Overload of builder function field(FieldMaker)

### ISSUE THREAD

**Issue by fmcarvalho** [cojen/Maker#12]
It would be useful to have a builder function `field(FieldMaker)` that receives a `FieldMaker` rather than a weakly typed `String`.

This builder would be flawless between the field declaration and its use. 

Naif use of Strings may lead to inconsistent  refactoring between the field declaration e.g. `maker.addField(clazz, "fieldName")` and its usage, e.g. `handleFun.field("fieldName")...`

**Comment by broneill** [comment]
I've considered this, but something about it doesn't quite feel right to me. What happens if the FieldMaker instance comes from another ClassMaker? Is the FieldMaker just passing the name or should additional type checks be added?

Does supporting this feature also extend to MethodMaker? That is, should I be able to call invoke(MethodMaker, ...) instead of passing the name and finding a matching signature?

Adding a `FieldMaker.name()` method offers the feature you want, in a fashion which seems clearer to me. The feature can also be added to MethodMaker without causing any confusion. I wouldn't add the feature to ClassMaker, because the class name can change which it's finished.

**Comment by fmcarvalho** [comment]
1. "_Is the FieldMaker just passing the name or should additional type checks be added?_" - IMO no checks needed. Accessibility checks are made at runtime by JVM. The resulting class is still wellformed even if it is trying to access inaccessible members. That is the approach followed by some dynamic generators. 

2. "_should I be able to call invoke(MethodMaker, ...)_" - Yes, it makes sense to me. Again no checks needed.

3. "_Adding a FieldMaker.name() method offers the feature you want_" - Yes, it definitely helps. Although, I still think that having a `field(FieldMaker)` would be safer.

**Comment by broneill** [comment]
One reason I don't like adding overloads because it adds more bloat to the javadocs. If I'm going to add it, it needs to offer a special new feature, and so adding additional checks might be useful. If the initial version of the overload doesn't do any checks, adding them later might break compatibility. Although the JVM does it's own checks, they can often be more difficult to understand.

There's also odd cases that just confuse me. Consider the case that I define a FieldMaker in one class and then I pass it to the MethodMaker of another class. Is this just extracting the field name or am I intending to access the field in the other class? If so, does this mean that the Field object which is returned is bound to the other class? That's not how it's supposed to work.

The safe thing to do is to check that the FieldMaker instance is bound to the same class as the MethodMaker it's being passed to. But does this create more confusion? What if I wanted to obtain a field in the other class? This is achieved by calling the field method on a Variable instance. Should this method also be overloaded to accept a FieldMaker? It makes my head spin thinking about these different forms.

**Comment by broneill** [comment]
I added the name method, which will appear in the next release.
